LANG_VARIANTS_TO_ISO = {
    'english': 'en', 'english, middle (1100-1500)': 'en', 'en': 'en',
    'french': 'fr', 'french, middle (ca.1400-1600)': 'fr', 'fr': 'fr',
    'german': 'de', 'de': 'de',
    'persian': 'fa', 'farsi': 'fa', 'fa': 'fa', 'iranian (other)': 'fa',
    'arabic': 'ar', 'ar': 'ar',
    'spanish': 'es', 'es': 'es',
    'multiple languages': 'mul',
    'portuguese': 'pt', 'pt-br': 'pt', 'pt': 'pt',
    'italian': 'it', 'it': 'it',
    'romanian': 'ro', 'ro': 'ro',
    'turkish': 'tr', 'tr': 'tr',
    'polish': 'pl', 'pl': 'pl',
    'bulgarian': 'bg', 'bg': 'bg',
    'tamil': 'ta', 'ta': 'ta',
    'japanese': 'ja', 'ja': 'ja',
    'norwegian': 'no', 'bokmål, norwegian; norwegian bokmål': 'no',
    'norwegian nynorsk; nynorsk, norwegian': 'no', 'no': 'no',
    'urdu': 'ur',
    'dutch': 'nl', 'dutch, middle (ca.1050-1350)': 'nl', 'nl': 'nl',
    'finnish': 'fi', 'fi': 'fi',
    'marathi': 'mr',
    'chinese': 'zh', 'zh-cn': 'zh',
    'swedish': 'sv', 'sv': 'sv',
    'icelandic': 'is',
    'malayalam': 'ml',
    'croatian': 'hr',
    'estonian': 'et',
    'greek, modern (1453-)': 'el', 'greek, ancient (to 1453)': 'grc',
    'russian': 'ru', 'ru': 'ru',
    'kurdish': 'ku',
    'danish': 'da', 'da': 'da',
    'hindi': 'hi',
    'filipino; pilipino': 'tl', 'tagalog': 'tl', 'tl': 'tl',
    'serbian': 'sr', 'sr': 'sr',
    'bengali': 'bn',
    'malay': 'ms', 'ms': 'ms',
    'catalan; valencian': 'ca', 'ca': 'ca',
    'czech': 'cs', 'cs': 'cs',
    'vietnamese': 'vi', 'vi': 'vi',
    'armenian': 'hy',
    'georgian': 'ka',
    'kannada': 'kn',
    'korean': 'ko', 'ko': 'ko',
    'nepali': 'ne',
    'slovak': 'sk',
    'telugu': 'te',
    'hungarian': 'hu', 'hu': 'hu',
    'azerbaijani': 'az',
    'lithuanian': 'lt', 'lt': 'lt',
    'ukrainian': 'uk',
    'faroese': 'fo',
    'basque': 'eu',
    'indonesian': 'id', 'id': 'id',
    'macedonian': 'mk',
    'maltese': 'mt',
    'gujarati': 'gu', 'gu': 'gu',
    'amharic': 'am',
    'albanian': 'sq', 'sq': 'sq',
    'assamese': 'as',
    'panjabi; punjabi': 'pa',
    'latvian': 'lv',
    'bosnian': 'bs',
    'thai': 'th', 'th': 'th',
    'afrikaans': 'af',
    'mongolian': 'mn',
    'galician': 'gl', 'gl': 'gl',
    'slovenian': 'sl', 'sl': 'sl',
    'aromanian; arumanian; macedo-romanian': 'rup',
    'may languages': 'myn', 'australian languages': 'aus',
    'duala': 'dua', 'aleut': 'ale',
    'un': 'und', 'undetermined': 'und'
}

ISO_TO_LANG = {
    'en':'English',
    'fr':'French',
    'de':'German',
    'fa':'Persian',
    'ar':'Arabic',
    'es':'Spanish',
    'mul':'Multiple languages',
    'pt':'Portuguese',
    'it':'Italian',
    'ro':'Romanian',
    'tr':'Turkish',
    'pl':'Polish',
    'bg':'Bulgarian',
    'ta':'Tamil',
    'ja':'Japanese',
    'no':'Norwegian',
    'ur':'Urdu',
    'nl':'Dutch',
    'fi':'Finnish',
    'mr':'Marathi',
    'zh':'Chinese',
    'sv':'Swedish',
    'is':'Icelandic',
    'ml':'Malayalam',
    'hr':'Croatian',
    'et':'Estonian',
    'el':'Greek',
    'grc':'Ancient Greek',
    'ru':'Russian',
    'ku':'Kurdish',
    'da':'Danish',
    'hi':'Hindi',
    'tl':'Tagalog / Filipino',
    'sr':'Serbian',
    'bn':'Bengali',
    'ms':'Malay',
    'ca':'Catalan / Valencian',
    'cs':'Czech',
    'vi':'Vietnamese',
    'hy':'Armenian',
    'ka':'Georgian',
    'kn':'Kannada',
    'ko':'Korean','ne':'Nepali',
    'sk':'Slovak',
    'te':'Telugu',
    'hu':'Hungarian',
    'az':'Azerbaijani',
    'lt':'Lithuanian',
    'uk':'Ukrainian',
    'fo':'Faroese',
    'eu':'Basque',
    'id':'Indonesian',
    'mk':'Macedonian',
    'mt':'Maltese',
    'gu':'Gujarati',
    'am':'Amharic',
    'sq':'Albanian',
    'as':'Assamese',
    'pa':'Punjabi',
    'lv':'Latvian',
    'bs':'Bosnian',
    'th':'Thai',
    'af':'Afrikaans',
    'mn':'Mongolian',
    'gl':'Galician',
    'sl':'Slovenian',
    'rup':'Aromanian (Macedo-Romanian)',
    'myn':'Mayan languages',
    'aus':'Australian languages',
    'dua':'Duala',
    'ale':'Aleut',
    'und':'Undetermined'
}

def lang_to_iso(value: str) -> str:
    s = value.strip().lower() if isinstance(value, str) else ''
    if not s:
        return 'und'
    if s in LANG_VARIANTS_TO_ISO:
        return LANG_VARIANTS_TO_ISO[s]
    if '-' in s: 
        base = s.split('-')[0]
        if base in ISO_TO_LANG:
            return base
    if s in ISO_TO_LANG:
        return s
    return 'und'

def iso_to_display(code: str) -> str:
    return ISO_TO_LANG.get(code, code.upper())
